--------------------------------------------------------
--  文件已创建 - 星期二-八月-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODSPHOTO
--------------------------------------------------------

  CREATE TABLE "RAINBOWSIX6"."GOODSPHOTO" 
   (	"PHOTO_ID" NUMBER(12,0), 
	"PROID" NUMBER(12,0), 
	"DES" NUMBER(12,0), 
	"PHOTO" BLOB, 
	"RANK" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into RAINBOWSIX6.GOODSPHOTO
SET DEFINE OFF;
Insert into RAINBOWSIX6.GOODSPHOTO (PHOTO_ID,PROID,DES,RANK) values (1,20,2,2);
--------------------------------------------------------
--  DDL for Index GOODSPHOTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAINBOWSIX6"."GOODSPHOTO_PK" ON "RAINBOWSIX6"."GOODSPHOTO" ("PHOTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GOODSPHOTO
--------------------------------------------------------

  ALTER TABLE "RAINBOWSIX6"."GOODSPHOTO" ADD CONSTRAINT "GOODSPHOTO_PK" PRIMARY KEY ("PHOTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RAINBOWSIX6"."GOODSPHOTO" MODIFY ("PHOTO_ID" NOT NULL ENABLE);
