--------------------------------------------------------
--  文件已创建 - 星期四-八月-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "neusoft_wv"."GOODS" 
   (	"PROID" VARCHAR2(20 BYTE), 
	"COMID" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"STOCK" NUMBER(9,0), 
	"PHOTO" BLOB, 
	"PHOTOTYPE" VARCHAR2(20 BYTE), 
	"PHOTONAME" VARCHAR2(30 BYTE), 
	"GOODDESC" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(8,2), 
	"WEIGHT" NUMBER(8,2), 
	"GOODDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into RAINBOWSIX6.GOODS
SET DEFINE OFF;
Insert into RAINBOWSIX6.GOODS (PROID,COMID,STATE,STOCK,PHOTOTYPE,PHOTONAME,GOODDESC,TYPE,TITLE,PRICE,WEIGHT,GOODDATE) values ('2','00001',null,null,null,null,null,null,'first',10,null,to_date('01-JAN-18','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index GOODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAINBOWSIX6"."GOODS_PK" ON "RAINBOWSIX6"."GOODS" ("PROID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "RAINBOWSIX6"."GOODS" ADD CONSTRAINT "GOODS_PK" PRIMARY KEY ("PROID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RAINBOWSIX6"."GOODS" MODIFY ("PROID" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."GOODS" MODIFY ("COMID" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."GOODS" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."GOODS" MODIFY ("PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."GOODS" MODIFY ("GOODDATE" NOT NULL ENABLE);
