--------------------------------------------------------
--  文件已创建 - 星期三-八月-15-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGISTICS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOGISTICS" 
   (	"LOGISTICSID" NUMBER(20,0), 
	"ORDERID" NUMBER(20,0), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"EXPRESSNUMBER" NUMBER(20,0), 
	"CONSIGNEE" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."LOGISTICSID" IS '物流id';
 
   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."ORDERID" IS '订单id';
 
   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."ADDRESS" IS '收货地址';
 
   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."EXPRESSNUMBER" IS '快递单号';
 
   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."CONSIGNEE" IS '收货人';
 
   COMMENT ON COLUMN "SYSTEM"."LOGISTICS"."PHONE" IS '手机号';
REM INSERTING into SYSTEM.LOGISTICS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LOGISTICS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LOGISTICS_PK" ON "SYSTEM"."LOGISTICS" ("LOGISTICSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOGISTICS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGISTICS" ADD CONSTRAINT "LOGISTICS_PK" PRIMARY KEY ("LOGISTICSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."LOGISTICS" MODIFY ("LOGISTICSID" NOT NULL ENABLE);
