--------------------------------------------------------
--  文件已创建 - 星期四-八月-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAKER
--------------------------------------------------------

  CREATE TABLE "RAINBOWSIX6"."MAKER" 
   (	"MAKER_NO" NUMBER(12,0), 
	"MAKER_NAME" VARCHAR2(128 BYTE), 
	"MAKER_PASSWORD" VARCHAR2(128 BYTE), 
	"ADDRESS" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"MAKER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RAINBOWSIX6.MAKER
SET DEFINE OFF;
Insert into RAINBOWSIX6.MAKER (MAKER_NO,MAKER_NAME,MAKER_PASSWORD,ADDRESS,EMAIL,PHONE_NUMBER,MAKER_ID) values (2,'23','234','234','23423','234','2');
--------------------------------------------------------
--  DDL for Index SYS_C0011266
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAINBOWSIX6"."SYS_C0011266" ON "RAINBOWSIX6"."MAKER" ("MAKER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MVO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAINBOWSIX6"."MVO_UK1" ON "RAINBOWSIX6"."MAKER" ("MAKER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAKER
--------------------------------------------------------

  ALTER TABLE "RAINBOWSIX6"."MAKER" ADD CONSTRAINT "MVO_UK1" UNIQUE ("MAKER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("MAKER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("MAKER_PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" ADD PRIMARY KEY ("MAKER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RAINBOWSIX6"."MAKER" MODIFY ("MAKER_ID" NOT NULL ENABLE);
