--------------------------------------------------------
--  文件已创建 - 星期四-八月-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_ROLE
--------------------------------------------------------

  CREATE TABLE "RAINBOWSIX6"."USER_ROLE" 
   (	"ROLENAME" VARCHAR2(16 BYTE), 
	"MENUID" NUMBER(12,0), 
	"DETIAL" VARCHAR2(500 BYTE), 
	"ROLEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RAINBOWSIX6.USER_ROLE
SET DEFINE OFF;
Insert into RAINBOWSIX6.USER_ROLE (ROLENAME,MENUID,DETIAL,ROLEID) values ('admin',null,'管理员',2);
--------------------------------------------------------
--  DDL for Index USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAINBOWSIX6"."USER_ROLE_PK" ON "RAINBOWSIX6"."USER_ROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_ROLE
--------------------------------------------------------

  ALTER TABLE "RAINBOWSIX6"."USER_ROLE" MODIFY ("ROLENAME" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."USER_ROLE" MODIFY ("ROLEID" NOT NULL ENABLE);
 
  ALTER TABLE "RAINBOWSIX6"."USER_ROLE" ADD CONSTRAINT "USER_ROLE_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
